var PORT = process.env.PORT || 3000;
var moment = require('moment');
var express = require('express');
var app = express();
var http = require('http').Server(app); //http server. anything express app listens to, the server should as well
var io = require('socket.io')(http);

app.use(express.static(__dirname + '/public'));

// set of key value pairs that will be stored:
// socket.id (generated by socket io), chat room name, and user name
var clientInfo = {};

// a function that sends a list of users to the chat window when it is triggered
// (@currentUsers in this case)
function sendCurrentUsers (socket) {
	var info = clientInfo[socket.id];
	var users = [];

	// if array is blank, send nothing
	if (typeof info === 'undefined') {
		return;
	}

	//each time a user joins, then the the user is pushed to 'user' array
	Object.keys(clientInfo).forEach(function (socketId) {
		var userInfo = clientInfo[socketId];

		if (info.room === userInfo.room) {
			users.push(userInfo.name);
		}
	});

	//message emmited when function is triggered
	socket.emit('message', {
		name: 'System',
		text: 'Current users: ' + users.join(', '),
		timestamp: moment().valueOf()
	});
}

// Socket Listening fo the events:
// Join Room, disconnect (from room), message (when sent)
io.on('connection', function (socket) {
	// when user connected using web browser
	console.log('User connected via socket.io!');

	// Emits that user joined the room to everyone except the user itself (broadcast)
	socket.on('joinRoom', function (req) {
		clientInfo[socket.id] = req;
		socket.join(req.room);
		socket.broadcast.to(req.room).emit('message', {
			name: 'System',
			text: req.name + ' has joined!',
			timestamp: moment().valueOf()
		});
	});

	// triggered when user disconnects from the chat room
	socket.on('disconnect', function () {
		var userData = clientInfo[socket.id];

		if (typeof userData !== 'undefined') {
			socket.leave(userData.room);
			io.to(userData.room).emit('message', {
				name: 'System',
				text: userData.name + ' has left!',
				timestamp: moment().valueOf()
			});
			delete clientInfo[socket.id];
		}
	});

	// Send that message that was outputted
	socket.on('message', function (message) {
		console.log('Message received: ' + message.text);

		//checks if messa
		if (message.text === '@currentUsers') {
			sendCurrentUsers(socket);
		} else {
			message.timestamp = moment().valueOf();
			//emits message only to people that are in the same room
			io.to(clientInfo[socket.id].room).emit('message', message);	
		}
	});

	// Terminal Message emitted when user enters the chat App
	socket.emit('message', {
		name: 'System',
		text: 'Welcome to the chat application!',
		timestamp: moment().valueOf()
	});
});

// server notification when it starts running
http.listen(PORT, function () {
	console.log('Server started!');
});